name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou um PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Step]
      - uses: actions/checkout@v3
      - name: "Lint"
        run: "npm run lint"
        
      
